name: server
version: 0.0.1
description: Completion system for Vim
#author: teja <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  jaguar: '>=0.2.5 <0.3.0'
  scribe: '0.2.0'
  args: '>=0.13.7 <0.14.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
