name: icu_server
version: 0.0.2
description: Completion system for Vim
author: Raiv Teja Gudapati <tejainece@gmail.com>
homepage: https://github.com/tejainece/icompleteu

environment:
  sdk: '>=1.0.0 <2.0.0'

executables:
  icu: icu

dependencies:
  jaguar: '>=0.2.6 <0.3.0'
  scribe: '>=0.2.0 <0.3.0'
  args: '>=0.13.7 <0.14.0'
  crypto: '>=2.0.0 < 3.0.0'
  path: '>=1.4.1 <2.0.0'
  dart_analysis_client: '>=0.0.2 <0.1.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
